export const FETCH_DETAIL = 'FETCH_DETAIL';
export const FETCH_READY_DETAIL = 'FETCH_READY_DETAIL';
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';
export const FETCH_DETAIL_ERROR = 'FETCH_DETAIL_ERROR';

export const UPDATE_STATE_AFTER_SOLVE_QUESTION = 'UPDATE_STATE_AFTER_SOLVE_QUESTION';
