language:
  - ruby
rvm:
  - 2.3.0
install:
  - gem install bundler
  - bundle install
  - npm install -g npm@2
  - rake db:create
env:
  global:
    - RAILS_ENV=test
script:
  - npm run dev
  - rails s
