export const FETCH_LECTURE = 'FETCH_LECTURE';
export const FETCH_READY_LECTURE = 'FETCH_READY_LECTURE';
export const FETCH_LECTURE_SUCCESS = 'FETCH_LECTURE_SUCCESS';
export const FETCH_LECTURE_ERROR = 'FETCH_LECTURE_ERROR';

export const UNMOUNT_LECTURE = 'UNMOUNT_LECTURE';
export const unmountLecture = () => ({
  type: UNMOUNT_LECTURE
});


export const UPDATE_STATE_AFTER_SOLVE_QUESTION = 'UPDATE_STATE_AFTER_SOLVE_QUESTION';
