export const INIT_GOOGLE_SERVICE = 'INIT_GOOGLE_SERVICE';

export const LOGIN_GOOGLE_SERVICE = 'LOGIN_GOOGLE_SERVICE';
export const SUCCESS_LOGIN_GOOGLE_SERVICE = 'SUCCESS_LOGIN_GOOGLE_SERVICE';
export const FAIL_LOGIN_GOOGLE_SERVICE = 'FAIL_LOGIN_GOOGLE_SERVICE';

export const LOGOUT_GOOGLE_SERVICE = 'LOGOUT_GOOGLE_SERVICE';
export const SUCCESS_LOGOUT_GOOGLE_SERVICE = 'SUCCESS_LOGOUT_GOOGLE_SERVICE';
export const FAIL_LOGOUT_GOOGLE_SERVICE = 'FAIL_LOGOUT_GOOGLE_SERVICE';

export const USER_IS_SIGNEDIN = 'USER_IS_SIGNEDIN';
export const USER_ISNOT_SIGNEDIN = 'USER_ISNOT_SIGNEDIN';
