export const REQUEST_LECTURE_ANALYSIS = 'REQUEST_LECTURE_ANALYSIS';
export const SUCCESS_REQUEST_LECTURE_ANALYSIS = 'SUCCESS_REQUEST_LECTURE_ANALYSIS';
export const FAIL_REQUEST_LECTURE_ANALYSIS = 'FAIL_REQUEST_LECTURE_ANALYSIS';
