
export const FETCH_MY_CHANNEL = 'FETCH_MY_CHANNEL';
export const FETCH_READY_MY_CHANNEL = 'FETCH_READY_MY_CHANNEL';
export const FETCH_MY_CHANNEL_SUCCESS = 'FETCH_MY_CHANNEL_SUCCESS';
export const FETCH_MY_CHANNEL_ERROR = 'FETCH_MY_CHANNEL_ERROR';

export const DELETE_MY_CHANNEL_ITEM = 'DELETE_MY_CHANNEL_ITEM';
export const DELETE_READY_MY_CHANNEL_ITEM = 'DELETE_READY_MY_CHANNEL_ITEM';
export const DELETE_MY_CHANNEL_ITEM_SUCCESS = 'DELETE_MY_CHANNEL_ITEM_SUCCESS';
export const DELETE_MY_CHANNEL_ITEM_ERROR = 'DELETE_MY_CHANNEL_ITEM_ERROR';
export const DELETE_MY_CHANNEL_ITEM_FIN = 'DELETE_MY_CHANNEL_ITEM_FIN';
